// <autogenerated>
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// </autogenerated>

using System;   

public class T4Demo
{
   static void Main()
   {
      Console.WriteLine("This is a very, very simple T4 demo application :-)");
   }
}

